Network_Scanner
SoorajModi/ContributeAnythingGryphHacks23 pull request #12
Opened 2023-05-27 01:50 UTC by Devil-Code

**Why**

Assignment!!!!

**What**

Just a simple Code!!!!!

**Verification**

Run It!!!

**Checklist:**

None that I can think of!!!

- [ ] This contribution abides by all rules listed in `docs/Rules.md`

2023-05-27 02:07 UTC, SoorajModi requested changes
- Add a README following all rules
- Improve the pull request template, look at #1 for an example submission

2023-05-27 02:29 UTC, MarshallAsch requested changes

2023-05-27 02:29 UTC, MarshallAsch commented on submissions/network_scanner/README.md
> +$ python3 network_scanner.py
You can put these into a codeblock by using the 

````
```
my code
```
````

2023-05-27 02:29 UTC, MarshallAsch commented on submissions/network_scanner/network_scanner.py
While its technically not against the rules to submit school assignments. Please do not submit school assignments.

2023-05-28 02:33 UTC, MarshallAsch approved these changes

2023-05-28 03:31 UTC, SoorajModi approved these changes

2023-05-28 03:32 UTC, merged