added array_sort_c
SoorajModi/ContributeAnythingGryphHacks23 pull request #14
Opened 2023-05-27 02:00 UTC by DevinForr

**Why**

My submission for the Contribute Anything Workshop
---

**What**

I added a ReadMe and the program sort.c
---

**Verification**

Run sort.c to see how it works
---

**Checklist:**

- [x] This contribution abides by all rules listed in `docs/Rules.md`

2023-05-27 02:23 UTC, SoorajModi requested changes

2023-05-27 02:23 UTC, SoorajModi commented on submissions/array_sort_c/sort.c
> +}
Looks good overall, but please add newlines to the end of you files and look at example #1 for how to format your pull request template

2023-05-27 02:34 UTC, MarshallAsch requested changes
Looks good, small change request for the README formatting

2023-05-27 02:34 UTC, MarshallAsch commented on submissions/array_sort_c/README.md
> +Why I contributed it: It is a good example of the usage of qsort
Try to use markdown formatting for the readme, it makes it quite nice to read and show up nicely in the UI when it gets rendered. [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) is some more information about markdown

2023-05-28 22:41 UTC, SoorajModi approved these changes

2023-05-29 02:23 UTC, merged