init
SoorajModi/ContributeAnythingGryphHacks23 pull request #15
Opened 2023-05-27 02:03 UTC by achin04

**Why**

In case anyone needs videos in their application for their project. You can use this to get the youtube videos into mp4 format.
---

**What**

A youtube downloader for any Gryph Hackers
---

**Verification**

Must install pytube by typing "pip3 install pytube" into the terminal to run
To use this program you must have `python3` installed.
Once python is installed the following commands can be used to run it.
```bash
$ cd submissions/GryphHacksVidDownloader/ytgui.py
```
```bash
$ ./ytgui.py
```
---

**Checklist:**

- [x ] This contribution abides by all rules listed in `docs/Rules.md`

2023-05-27 02:27 UTC, SoorajModi requested changes

2023-05-27 02:27 UTC, SoorajModi commented on submissions/GryphHacksVidDownloader/ytgui.py
> +    app.mainloop()
Please add a newline to the end of you files, also change the name of the PR to something more meaningful, look at #1 for an example

2023-05-27 02:36 UTC, MarshallAsch requested changes

2023-05-27 02:36 UTC, MarshallAsch commented on submissions/GryphHacksVidDownloader/README.md
> +Must instal pytube by typling "pip3 install pytube" into terminal to run
spelling
```suggestion
Must instal pytube by typling `pip3 install pytube` into terminal to run
```

using code blocks is a nice way of making the commands stand out in a line of text

2023-05-28 22:42 UTC, SoorajModi approved these changes

2023-05-29 02:24 UTC, merged