This is Mina's password login program
SoorajModi/ContributeAnythingGryphHacks23 pull request #16
Opened 2023-05-27 02:18 UTC by awadmina

**Why**

I wanted to try to fork in github
---

**What**

password file and README file
---

**Verification**

run "python3 password/password.py" in terminal to run the program. make sure you have python3 installed
---

**Checklist:**

- [ x] This contribution abides by all rules listed in `docs/Rules.md`

2023-05-27 02:32 UTC, SoorajModi commented
Take a look at #1 for an example, improve the name of the PR, also the checkbox should look like `[x]` not `[ x]`

2023-05-27 02:32 UTC, SoorajModi requested changes

2023-05-27 02:32 UTC, SoorajModi commented on submissions/password/README.md
> +if you want to run in terminal type "python3 password/password.py"
Missing the following in the README:
- List of contributors
- Why you contributed it

2023-05-27 02:42 UTC, MarshallAsch requested changes

2023-05-27 02:42 UTC, MarshallAsch commented on submissions/password/README.md
Try to use markdown formatting to make the different sections easy to read. See [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for some more info on markdown syntax

2023-05-27 02:42 UTC, MarshallAsch commented on submissions/password/password.py
SPACING!!!!! Leave some whitespace in the code to visionally separate the code into meaningful blocks. As a single large wall of text its a bit difficult to tell whats happening and what each component does.

2023-05-27 02:42 UTC, MarshallAsch commented on submissions/password/password.py
> + print("what do you what your username to be?")
Does this work? it looks like your indentation is inconsistent in the file?

2023-05-28 22:46 UTC, SoorajModi commented
Hey @awadmina there are a few outstanding issues left to resolve for this PR, please address them ASAP so we can merge in your contribution. To make changes you can push to your branch, and the changes should appear on this PR.

2023-05-30 21:46 UTC, closed without merging