DogOrCat
SoorajModi/ContributeAnythingGryphHacks23 pull request #17
Opened 2023-05-27 02:28 UTC by Bonew13

**Why**

I am contributing to this to make a better society.

---

**What**

This pull request contains a new file called dog or cat.
---

**Verification**

This program shows an image of a cat or a dog.

*******

To Run the program, ensure your path leads to the
DogOrCat folder.

Once you are in the correct directory. type 'python catordog.py'.

*******
---

**Checklist:**

- [x] This contribution abides by all rules listed in `docs/Rules.md`

2023-05-27 02:38 UTC, SoorajModi commented
Also, improve the name of the README and the format of the pull request template, take a look at #1 for an example submission

2023-05-27 02:38 UTC, SoorajModi requested changes

2023-05-27 02:38 UTC, SoorajModi commented on submissions/hello_world/DogOrCat/README.txt
> +*******
Your README should be a markdown file, and missing the following info:
- List of contributors
- Why you contributed it

2023-05-27 02:45 UTC, MarshallAsch requested changes

2023-05-27 02:45 UTC, MarshallAsch commented on submissions/hello_world/DogOrCat/DogOrCat.py
> +
remove excess whitespace
```suggestion
```

2023-05-27 02:45 UTC, MarshallAsch commented on submissions/hello_world/DogOrCat/README.txt
> +*******
You can use markdown section blocks here. See [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

2023-05-27 02:45 UTC, MarshallAsch commented on submissions/hello_world/DogOrCat/README.txt
This should be be a `.md` file not a `.txt` file

2023-05-28 22:44 UTC, SoorajModi commented
Hey @Bonew13, there are a few outstanding requests for change in this PR, please try to have these issues resolved ASAP so we can merge in your contribution

2023-05-30 21:46 UTC, closed without merging