sample
SoorajModi/ContributeAnythingGryphHacks23 pull request #18
Opened 2023-05-27 02:33 UTC by ShreyasJ1P

**Why**
<to practice pull and push on git >

---

**What**

---

**Verification**

---

**Checklist:**

- [ ] This contribution abides by all rules listed in `docs/Rules.md`

2023-05-27 02:40 UTC, SoorajModi commented on submissions/Welcome_to_GryphHacks /README.md
> +This program was created by [Shreyas Jeevan Prakash].
Nit: instead of `[Shreyas Jeevan Prakash]` try `[Shreyas Jeevan Prakash](https://github.com/ShreyasJ1P)` so you can add a link to your profile

2023-05-27 02:40 UTC, SoorajModi commented
Improve the name of the pull request and the pull request template formatting, take a look at #1 for an example

2023-05-28 02:39 UTC, MarshallAsch reviewed
This is a duplicate hello world program, it violates the rule that it can not contribute something that had already been done.

Other than that it looks good 😀

2023-05-28 02:40 UTC, MarshallAsch requested changes
(Accidentally marked it as a comment)

2023-05-28 22:44 UTC, SoorajModi approved these changes

2023-05-29 02:25 UTC, merged